version: '3'

services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
  admin:
    image: apache/dubbo-admin
    depends_on:
      - zookeeper
    ports:
      - 8080:8080
    environment:
      - admin.registry.address=zookeeper://192.168.1.5:2181
      - admin.config-center=zookeeper://192.168.1.5:2181
      - admin.metadata-report.address=zookeeper://192.168.1.5:2181